# =========================================================================

# YAML: demo/cylc/environment.yaml

# Email: henry.winterbottom@noaa.gov

# This program is free software: you can redistribute it and/or modify
# it under the terms of the respective public license published by the
# Free Software Foundation and included with the repository within
# which this application is contained.

# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# =========================================================================

# Description
# -----------

# This YAML-formatted file contains environment variables specific to
# a specific Cylc engine application/experiment; the respective
# environment variables will be appended to the Cylc engine
# environment.rc Jinja2-formatted file; this file is provided as an
# example.

# Author
# ------
# Henry R. Winterbottom

# Date
# ----
# 08 January 2023

# History
# -------
# 2023-01-08: Henry Winterbottom -- Original version.

# ----

# Define the Cylc engine application/experiment environment variables;
# these variables will be appended to the Cylc engine environment.rc
# Jinja2-formatted file.
ENVVAR_ONE: 1
ENVVAR_TWO: 2
ENVVAR_THREE: 3
